### ISSUE TITLE
Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by hemant9494** [KrunalLathiya/NodeJWTAuth#1]
On following the tutorial on 
https://appdividend.com/2018/02/07/node-js-jwt-authentication-tutorial-scratch/
and cloning repo and running i am getting this error repeatedly on node 10.6, npm 6.4

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/hemant/WebstormProjects/NodeJWTAuth/routes/user.route.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/hemant/WebstormProjects/NodeJWTAuth/server.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by kiranlm-cts** [comment]
did you tried `npm install` ?

**Comment by dragos199993** [comment]
when you use npm install --save bcrypt you might have an error which is caused by python path 
just use this command if you have this issues: 
`npm --add-python-to-path='true' --debug install --global windows-build-tools`
